// Client/Project Management Types

export type ClientType = 'Clients' | 'Projects' | 'Rentals' | 'Products' | string;
export type ClientStatus = 'Active' | 'Pending Payment' | 'Completed' | 'On Hold';
export type PaymentTerms = 'full' | 'partial' | 'recurring';
export type RecurringFrequency = 'monthly' | 'weekly' | 'quarterly' | 'yearly' | 'custom';
export type PaymentStatus = 'scheduled' | 'pending' | 'paid' | 'overdue';

export interface PaymentScheduleItem {
  scheduleId: string;
  dueDate: string;
  amount: number;
  status: PaymentStatus;
  paidDate?: string;
  transactionId?: string;
  autoGenerated?: boolean;
  generatedAt?: string;
  frequency?: RecurringFrequency;
  periodLabel?: string;
}

export interface RecurringSettings {
  frequency: RecurringFrequency;
  dayOfPayment: number;
  customDays?: number;
  startDate: string;
  endDate?: string | null;
  autoGenerate: boolean;
  generateAheadCount: number;
  lastGenerated?: string;
  nextDueDate?: string;
  totalGenerated?: number;
  isPaused?: boolean;
  pausedAt?: string | null;
  pausedReason?: string | null;
}

export interface ClientService {
  serviceId: string;
  serviceName: string;
  expectedAmount: number;
  paymentTerms: PaymentTerms;
  paymentSchedule?: PaymentScheduleItem[];
  recurring?: RecurringSettings;
}

export interface ClientBasicInfo {
  name: string;
  type: ClientType;
  status: ClientStatus;
  description: string;
  contactEmail: string;
  contactPhone: string;
  startDate: string;
  endDate?: string;
  createdBy: {
    userId: string;
    name: string;
  };
  createdAt: string;
}

export interface ClientFinancialSummary {
  totalExpectedIncome: number;
  totalReceivedIncome: number;
  totalPendingIncome: number;
  totalExpenses: number;
  netProfit: number;
}

export interface Client {
  id: string;
  basicInfo: ClientBasicInfo;
  services: ClientService[];
  financialSummary: ClientFinancialSummary;
  customExpenseCategories: string[];
}
